services:
  backend:
    build:
      context: ./DesafioApi
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
      - '5001:5001'
    environment:
      - ASPNETCORE_URLS=http://+:5000
    networks:
      - desafio-net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4200:80'
    depends_on:
      - backend
    networks:
      - desafio-net

networks:
  desafio-net:
    driver: bridge
